# -----------------------------------------------------------------------------
# docker-compose.prod.yml — KnowHowPagesEditor Production
#
# Usage: docker compose -f docker-compose.prod.yml up -d
# -----------------------------------------------------------------------------

services:
  # React/Vite client production build served by nginx
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: production    
    ports:
      - "3000:80"  # Web server    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - server
    networks:
      - app-network

  # Fastify server production
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: production
    ports:
      - "3001:3001"  # API server    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
